// AUTHORED from a real, verified src/jigsaw/loop.ts session —
// logs/jigsaw-2026-07-19T14-56-24-481Z.jsonl ($0.2396, 42 real API calls),
// converted by scripts/convert-jigsaw-log.ts and hand-reviewed. Not
// runtime-generated: the UI never calls the API (locked decision).

import type { TurnView } from "./data";

export const JIGSAW_TURNS: TurnView[] = [
  {
    speaker: "Teacher",
    phase: "luku",
    dialogueMove: "facilitate",
    said: "Tervetuloa! Tänään käytetään palapelimenetelmää: jokainen on saanut yhden luvun Leppilammen artikkelista. Lukekaa ensin oma kappaleenne rauhassa ja kirjoittakaa itsellenne lyhyet muistiinpanot — noin 50–100 sanaa siitä, mitkä ovat kappaleen tärkeimmät ajatukset ja mitä aiotte painottaa, kun opetatte sen omalle ryhmällenne.",
    costUSD: null,
  },
  {
    speaker: "Aino",
    phase: "luku",
    group: "ryhma1",
    said: "Okei, mä luen tän nyt huolella ja kirjoitan itelleni muistiinpanot.\n\nNo siis tän kappaleen ydinasia on se, että johtaja ei voi sanoa \"näin se tehdään\" ylhäältä päin, vaan hän pitää kävellä henkilöstön rinnalla ja kysyä kysymyksiä. Johtajalla pitää olla selkeä visio, mutta se pitää kehittää yhdessä.\n\nKeskeiset käsitteet: experiential learning eli oppiminen tekemisen kautta, jossa ihminen kontrolli omaa oppimistaan. Sitten tää iceberg-malli eli jäävuori — näkyy vain kärki mutta alle jää piiloon organisaation kulttuuri, arvot, tunteet.\n\nTärkeä pointti: muutos ei tule säännöistä vaan siitä, että kaikki osallistuvat prosessiin ja heijastuvat tekemisestään.\n\nEsimerkki: Jos johtaja haluaa muuttaa organisaation kulttuurin, se ei onnistu käskyllä. Henkilöstö kuuntelee vähän aikaa, sitten vastustaa, muodostuu klikkejä. Mutta jos johtaja ottaa kaikki mukaan pohtimaan arvoja ja tavoitteita, se onnistuu.",
    costUSD: 0.00740525,
  },
  {
    speaker: "Nea",
    phase: "luku",
    group: "ryhma1",
    said: "Okei, niin mä luen tän kappaleensa huolella... Mut hetkinen, mä haluan varmistaa että ymmärsin tehtävän oikein. Mä kirjoitan muistiinpanot itselleni, enkä jaa niitä muille? Ja sitten myöhemmin opetan tän kappaleeni Ainolle ja Leolle? Okei, selvä. Niin mä aloitan. Lukee kappaleita... Joo, okei, nyt mä kirjoitan nämä muistiinpanot itelleni: Kehitysprosessissa on kaksi päävaihetta - divergenssi (hajaantumisvaihe) ja konvergenssi (yhdistymisvaihe). Divergenssissa kuunnellaan kaikkien kokemuksia ja etsitään erilaisia ratkaisumalleja. Konvergenssissa sovitaan mitkä kehitysongelmat otetaan käsittelyyn ja missä järjestyksessä. Tärkeää on ettei aloiteta liian monta prosessia kerralla. Jäädään mielessä erityisesti tää kohta siitä, että jokainen osallistuu ainakin yhteen kehitysryhmään - kaikki osallistuu, ei jäädä sivuun. Ja sit tää jatkuvan arvioinnin idea - prosessin aikana arvioidaan säännöllisesti ja kerrotaan kaikille, miten menee. Konkreettinen esimerkki: jos työpaikalla halutaan parantaa kommunikaatiota, ensin avataan kaikille, mitä mieltä ovat nykytilasta, sitten sovitaan kehityskohteista ja vastuuhenkilöistä, ja koko prosessin ajan seurataan miten etenee ja säädellään tukea tarpeen mukaan.",
    costUSD: 0.00824525,
  },
  {
    speaker: "Leo",
    phase: "luku",
    group: "ryhma1",
    said: "Okei, luen tän omassa rauhassa. Katotaan mitä täällä on...\n\nJoo, kirjotan muistiinpanot tähän:\n\nKOoperatiivisen kokouksen idea: kokoukset on usein turhaa aikaa hukkaavat, mutta hyvin johdettuja kokouksia voi käyttää malleina koko organisaation yhteistyökulttuurille.\n\nTärkeimmät asiat:\n1. Fyysinen ympäristö ja järjestely: istumajärjestys ympyrässä, paikka vaikuttaa, voidaan kokeilla ulkona. Ihmiset tulee paikalle ajoissa jos on kahvia.\n\n2. Agendajako ja ajanhallinta: agenda pitää jakaa ilmoituksiin, päätettäviin ja keskusteltaviin asioihin. Aika sovitaan etukäteen ja sitä noudatetaan. Agenda etukäteen osallistujille niin ei käytävän juoruja.\n\n3. Osallistaminen: pariutat ihmisiä, pienryhmät vaikeista asioista, kaikki vastaa (A, B, C -jako). Näin hiljaisetkaan osallistuvat. Arviointivaihe pareissa.\n\nEsimerkki: jos jotkut ei puhu kokouksissa, ne laitetaan pareittain miettimään ja sitten satunnaisesti joku parista kertoo. Näin kaikki tulee kuulluksi.",
    costUSD: 0.00900775,
  },
  {
    speaker: "Vilma",
    phase: "luku",
    group: "ryhma2",
    said: "Otetaan siis nämä muistiinpanot. Mä kirjoitan tähän omille muistiinpanoille...\n\nOkei, tärkeimmät jutut täältä:\n\n1. Kokemusten kautta oppiminen ja reflektio – ihminen motivoituu kun saa itse asettaa tavoitteensa ja päättää keinot. Reflektointi on tosi tärkeää, pitää osata katsoa taaksepäin ja oppia sekä onnistumisista että virheistä.\n\n2. Johtaja kulkee rinnalla – ei määrää ylhäältä, vaan kysyy avoimesti, on kiinnostunut, myöntää omat heikkoudet. Näin tiimi uskaltaa riskeerata ja epäonnistua ilman pelkoa.\n\n3. Jäävuoren malli – näkyvä osa (visio, rakenteet) on tärkeä, mutta piilotettu osa (kulttuuri, arvot, tunneilmapiiri) ratkaisee oikeasti. Muutos tapahtuu kun henkilöstö osallistuu koko prosessissa eikä vaan käsketään ylhäältä.\n\nEsimerkki: johtaja voisi firman strategiaa muutettaessa kuunnella kaikkien näkemykset arvoista ja tavoitteista, sitten tehdä lopullisen päätöksen itsenäisesti mutta perustellen – näin tiimi ymmärtää päätöstä vaikka ei olisikaan täysin samaa mieltä.",
    costUSD: 0.00780525,
  },
  {
    speaker: "Sami",
    phase: "luku",
    group: "ryhma2",
    said: "Okei, lukee oman kappaleen ja kirjoittaa muistiinpanot itselle.\n\nTärkeimmät ajatukset:\n\n1. JÄÄVUORIMALLI kehitystyössä – näkyvä osa (ongelmat, niiden ratkaiseminen) perustuu näkymättömään osaan (arvot, kulttuuri, kommunikaatio). Pitää tutkia molempia.\n\n2. DIVERGENSSI-KONVERGENSSI-SYKLI – ensin avataan mahdollisuudet ja kerätään erilaiset näkemykset (divergenssi), sitten sovitaan priorisoitu kehityssuunnitelma (konvergenssi). Ja kaiken alla Kolbin kokemuksellisen oppimisen ympyrä (kokemus-reflektio-teoria-testaus).\n\n3. VASTUU ja JATKUVA ARVIOINTI – jokainen kantaa omaa vastuutaan kehitysprojektissa, kriteerit sovitaan etukäteen, arvioidaan koko prosessin ajan \"paine ja tuki\" -tasapainolla. Ilman dokumentoituja tavoitteita ihmiset unohtavat mistä alettiin, mikä tappaa motivaation.\n\n4. Konkreettinen esimerkki: Työyhteisö alkaa kehittämishankkeen – ensin dialogissa kartoitetaan missä ollaan nyt (divergenssi), sitten sovitaan kolme priorisoiduinta tavoitetta ja kuka vastaa mistäkin, arvioidaan puolessa välissä ja koko prosessin ajan, lopuksi dokumentoidaan opittu. Seuraava sykli alkaa heti – osallistujilla on jo subconscious mental work meneillään.",
    costUSD: 0.00815775,
  },
  {
    speaker: "Otto",
    phase: "luku",
    group: "ryhma2",
    said: "Okei, lukuvaihe. Luen mun kappaleesta ja teen muistiinpanot.\n\nHuonot kokoukset on organisaatioiden suurin ajan hukkaaminen. Leppilampi sanoo että huonosti järjestetyt kokoukset alkaa myöhässä, ihmiset puhuivat vaan vähäsen, ilma hyppi aiheesta toiseen.\n\nKolme pääjuttu mun kappalees:\n\n1. FYYSINEN TILA JA AIKA: Missä ja miten istutaan on iso juttu. Ympyrä ilman pöytää on parempi kuin perinteinen pöytä. Aika pitää sopia etukäteen ja pitää sitä, ei saa jäädä kesken.\n\n2. OSALLISTUMINEN: Kaikki osallistuu jokaiseen vaiheeseen. Esim. pienryhmätyöskentelyllä, pari-keskustelulla ja niin sanotuilla \"kirjain-rooleilla\" (A, B, C) varmistetaan että ne hiljaisemmat ihmisetkin pääsee ääneen. \"Everyone is ready to report\" periaate.\n\n3. RAKENNE: Agenda kolmeen osaan (ilmoitukset, päätettävät, keskusteltavat). Arviointi ja seuraavan kokouksen suunnittelu on tärkeä osa, ei jätetä chaiselle.\n\nEsimerkki: kun mietitään uutta istumajärjestystä, ensin pari-keskustelu \"miksi me istutaan täällä\", sitten satunnainen kysely pareista, sit kokeilua.\n\nYdinasia: positiivinen keskinäisriippuvuus ja yksilöllinen vastuu näkyy konkreettisesti kokouksen käytännöissä.",
    costUSD: 0.00949525,
  },
  {
    speaker: "Teacher",
    phase: "opetus",
    dialogueMove: "facilitate",
    said: "Hyvä, muistiinpanot on tehty. Sitten opetusvuorot: käydään kappaleet järjestyksessä a, b, c, molemmissa ryhmissä. Opettaja selittää kappaleensa omin sanoin, ja sen jälkeen kumpikin kuulija esittää yhden tarkentavan kysymyksen, joihin opettaja vastaa.",
    costUSD: null,
  },
  {
    speaker: "Teacher",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "facilitate",
    said: "Aino, sun vuoro: opeta kappaleesi \"Cooperative leadership in action\" ryhmällesi.",
    costUSD: null,
  },
  {
    speaker: "Aino",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "propose",
    docRef: "a",
    said: "Okei, niin mun kappale käsittelee sitä, miten yhteisöllinen johtaminen toimii käytännössä. Siinä on kaksi isoa ideaa: ensinnäkin se, miten ihminen oppii ja mitä se vaatii johtajalta, ja toiseks se, miten organisaation kulttuuri muuttuu.\n\nNo, ensimmäinen juttu on se experiential learning eli oppiminen tekemisen kautta. Siinä ajatuksena on, että ihminen oppii ja kehittyy eniten silloin kun hän itse päättää mitä haluaa oppia ja miten sitä tavoittelee. Ei siis ylhäältä annetut säännöt, vaan ihminen reflektoi omaa tekemistään ja oppii virheistään.\n\nTässä kohtaa johtajan rooli on hirvittävän tärkeä. Johtaja ei voi vaan sanoa \"näin se tehdään\", vaan hän kävelee henkilöstön rinnalla, esittää kysymyksiä ja kuuntelee oikeasti. Johtajalla pitää olla selkeä visio ja tavoitteet, mut se kehitetään yhdessä. Se vaatii siltä demokraattisuutta — johtaja myöntää omat heikkoutensa ja on valmis oppimaan muilta.\n\nSitten tää toinen puoli on se organisaation muutos. Siinä käytetään jäävuorimalli, iceberg. Näkyvä osa on strategia ja rakenteet, mut pinnan alla on koko organisaation kulttuuri, arvot, tunteet. Jos johtaja haluaa muuttaa kulttuuria, se ei onnistu käskyllä. Henkilöstö kuuntelee vähän aikaa, sitten muodostuu klikkejä ja vastustusta. Mutta jos johtaja ottaa kaikki mukaan pohtimaan arvoja ja tavoitteita, muutos jää pysyväksi. Siinä oleellista on että kaikki osallistuu prosessiin alusta loppuun.",
    costUSD: 0.0037939000000000002,
  },
  {
    speaker: "Nea",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "challenge",
    said: "Joo, kiitos Aino. Mä jäin miettimään sitä, kun sä sanoit että johtaja kävelee henkilöstön rinnalla ja esittää kysymyksiä — miten se johtaja tietää, milloin hän saa ohjata ja milloin pitää antaa vaan henkilöstön tehdä omia virheitä? Siihen menee kai joku tieto siitä, mikä on turvallisen oppimisen raja?",
    costUSD: 0.0023217,
  },
  {
    speaker: "Aino",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "build",
    said: "No, joo, se on hyvä kysymys. Mun kappaleessa sanotaan, että johtaja on valmis kuuntelemaan ja ottamaan riskejä, mut siinä mainitaan myös että johtaja tietää, milloin keskustelua on ollut tarpeeksi ja pitää tehdä päätös. Siis johtaja tunnistaa sen hetken milloin aika on tehdä päätös. Mut tuo raja mihin sä kysyt, että missä kohdassa henkilöstö alkaa oppia virheistä turvallisesti — sitä mun kappale ei oikeasti käsittele. Mut vois sanoa että ku organisaatiossa on turvallinen kulttuuri ja johtaja kuuntelee oikeasti, niin siihen liittyy varmaan se että pienemmät virheet on ok, mutta suuremmissa asioissa johtaja ohjaa enemmän. Se on tavallaan luottamus- ja kokemuspohjaista.",
    costUSD: 0.0029869000000000002,
  },
  {
    speaker: "Leo",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "challenge",
    said: "Okei, joo kiitos Aino. Mä jäin miettimään sitä jäävuorimallia — sä sanoit että johtaja ei voi käskyllä muuttaa kulttuuria, koska henkilöstö muodostaa klikkejä ja vastustusta. Mut millä tavalla se muutos sitten leviää oikeasti läpi organisaation, jos se alkaa siitä että kaikki osallistuu pohtimaan arvoja yhdessä? Niinku, miten johtaja varmistaa, että se kulttuurin muutos jää pysyväksi eikä takas vaan vanhoihin tapoihin?",
    costUSD: 0.0029609000000000003,
  },
  {
    speaker: "Aino",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "build",
    said: "Niin, hyvä pointti Leo. Totta kai se ei ole niin yksinkertainen että kun osallistutaan kerran yhteen pohtimiseen, niin muutos vaan jää. Mut mun kappaleessa sanotaan että se prosessi, se \"footing process\" niinku sanotaan, se on jatkuva — että henkilöstöllä on aktiivinen rooli koko ajan, arvoja, normeja, sääntöjä pohditaan läpi. Ja siinä se oleellinen on se, että reflektio ja tuki tulee jokapäiväiseksi tavaksi organisaatiossa. Eli se ei oo yksittäinen tapahtuma vaan kulttuuri, missä kaikki kehittää itseään ja kannustaa muita. Että se pysyvyys tulee siitä, että reflektio ja yhteinen pohtiminen jää pysyväksi praktiiaksi, ei että johtaja vaan käskee muutoksen ja odottaa että se pysyy.",
    costUSD: 0.0034289,
  },
  {
    speaker: "Teacher",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "facilitate",
    said: "Vilma, sun vuoro: opeta kappaleesi \"Cooperative leadership in action\" ryhmällesi.",
    costUSD: null,
  },
  {
    speaker: "Vilma",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "propose",
    docRef: "a",
    said: "Okei, joten mun kappale käsittelee sitä, miten kooperatiivinen johtajuus toimii käytännössä. Siis miten se ei ole vaan teoriaa vaan oikeasti konkretisoidaan organisaatiossa.\n\nTärkeimmät jutut tässä on ensin se, että ihminen motivoituu parhaiten kun saa itse vaikuttaa omaan kehitykseensä. Ei siis vain tule käskyt ylhäältä, vaan yksilö asettaa omat tavoitteensa ja päättää miten ne saavutetaan. Ja tässä reflektio on tosi keskeistä – jokainen pitää osata katsoa taaksepäin omaan työhönsä ja oppia sekä onnistumisista että virheistä.\n\nSitten toinen iso juttu on johtajan rooli. Kooperatiivinen johtaja ei johda käskemällä, vaan kulkee henkilöstön rinnalla. Se tarkoittaa että hän kysyy avoimia kysymyksiä, on aidosti kiinnostunut, ja uskaltaa myöntää omat heikkoutensa. Kun tiimi näkee että johtaja on rehellinen ja oppii muistaan, niin he uskaltaa ottaa riskejä ja epäonnistua ilman pelkoa syyllisyydestä.\n\nJa sitten kolmanneksi on tämä jäävuoren malli, mikä kuvaa organisaatiota. Näkyvä osa – visiot, rakenteet, resurssit – on tärkeä, mut oikeesti muutos tapahtuu piilotetulla osalla: kulttuurissa, arvoissa, tunneilmapiirissä. Ja se piilotettu osa muuttuu vain jos henkilöstö osallistuu muutosprosessiin alusta loppuun, ei vaan tule käsky ylhäältä. Kun ihmiset saavat olla mukana määrittelemässä arvoja ja tavoitteita, ne tulee paljon tunnetuimmaksi omiksi.",
    costUSD: 0.0038769,
  },
  {
    speaker: "Sami",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "challenge",
    said: "Joo, hyvä selvitys Vilma. Mut nyt mä jäin miettimään tätä johtajan roolia – kun sä sanoit et kooperatiivinen johtaja myöntää omat heikkoutensa ja ottaa riskejä, niin miten se käytännössä toimii? Eli esimerkiksi jos johtaja sano avoimesti tiimille että \"hei, mä en tiedä miten tää ratkaistaan\", niin eikö se vähennä hänen auktoriteettiaan tai tee siitä epäpätevältä silmissä?",
    costUSD: 0.0024835,
  },
  {
    speaker: "Vilma",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "build",
    said: "No joo, se on ihan hyvä pointti Sami. Mun kappaleessa se kuvataan silleen että johtaja, joka on kuunnellut henkilöstöään aidon kiinnostuksen kanssa, niin sitten kun se tekee itsenäisen päätöksen, se ei vähennä auktoriteettiä vaan pikemminkin vahvistaa sitä. Koska tiimi näkee että päätös tehtiin oikeesti kuuntelemalla, ei vaan omasta pääs. Ja sitten se johtaja myöntää olevansa vastuussa siitä päätöksestä, mikä on tosi erilaista kuin se autoritaarinen \"tää on käsky eikä kysymys\". Mut siihen kuuluu se, että johtaja on oikeasti valmis ottamaan riskit – myöntää heikkoutensa, oppimassa olevansa. Siis se ei ole heikkous vaan se näytetään että organisaatiossa on ok epäonnistua ja kehittyä. Tavallaan ne niinku mallinnetaan sitä, mitä he odottavat muilta.",
    costUSD: 0.0032559,
  },
  {
    speaker: "Otto",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "challenge",
    said: "Joo, kiitos Vilma hyvästä selityksestä. Mut nyt mä jäin miettimään tätä jäävuoren mallia ja sitä piilotettua osaa – kun sä sanoit että muutos tapahtuu kulttuurissa ja arvoissa, niin miten johtaja konkretisesti vie sitä muutosta eteenpäin? Eli jos mulla on organisaatio jossa kulttuuri on ollut hyvin hierarkkinen ja pelkopohjainen, niin miten sä alat siitä liikkeelle että ihmiset alkaa haastamaan sitä vanhaaa?",
    costUSD: 0.0030633,
  },
  {
    speaker: "Vilma",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "build",
    said: "Joo, Otto, ihan olennainen kysymys. Mun kappaleessa se asiaan ei mennä niin syvällä, mut se mitä siellä sanotaan on että muutos tapahtuu nimenomaan konfliktien ratkaisun ja reflektion kautta. Eli se ei ole yksittäinen päätös \"nyt me olemme demokraattisia\", vaan pikemminkin se, että johtaja alkaa johtaa eri tavalla – kysyy avoimesti, myöntää heikkoutensa, ja antaa tilaa sille että tiimi voi ottaa riskejä. Ja sitten kun tiimi näkee että tämä on ok, että oppiminen on sallittua, niin kulttuuri alkaa hitaasti muuttua. Mut miten siihen siirtymävaiheeseen mennään hierarkkisesta, siis se on varmaan jäävuoren siihen piilotettuun osaan ja siihen prosessiin mitä käsitellään sun tai Samin kappaleissa paremmin.",
    costUSD: 0.0035799,
  },
  {
    speaker: "Teacher",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "facilitate",
    said: "Nea, sun vuoro: opeta kappaleesi \"Cooperative development of a work community\" ryhmällesi.",
    costUSD: null,
  },
  {
    speaker: "Nea",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "propose",
    docRef: "b",
    said: "Okei, niin mun kappale käsittelee sitä, miten työyhteisöä kehitetään yhteisöllisesti. Se on tavallaan käytännön malli, miten se kokeileminen ja oppiminen, mistä Aino puhui, oikeasti viedään läpi organisaatiossa.\n\nNiin, perustana on tällainen jäävuorimalli, joka näkyy diagrammissa. Siinä on kaksi päävaihetta: ensin divergenssi, joka on hajaantumisvaihe, ja sitten konvergenssi, joka on yhdistymisvaihe.\n\nDivergenssissä — siis ensin — kaikki osallistuu pohtimaan nykytilaa. Kuka tahansa voi sanoa mitä mieltä on, käytetään kyselyitä ja avoimia keskusteluita. Pointti on se, että jokainen saa näkökulmansa kuulluksi. Siinä pohditaan, mitkä on yhteisön vahvuudet ja mitkä on ne asiat, mitkä vaatii kehittämistä. Konkreettinen esimerkki: jos mä työtään paikalla ja huomaan että kommunikaatio ei toimi, niin siihen tulee avoin keskustelu, mihin tämä johtuu.\n\nSitten konvergenssissä sovitaan, mitkä nuo kehitysongelmat otetaan käsittelyyn ja missä järjestyksessä. Tässä on tärkeää, ettei aloiteta liian monta projektia kerralla — se johtaa vaan siihen että kaikki hajallaan ja mitään ei saada valmiiksi. Jokaiselle kehityskohteelle nimetään vastuuhenkilöt ja sovitaan tavoitteet.\n\nMut mitä tekee tän mallin erityiseksi, on se että koko prosessin ajan arvioidaan jatkuvasti. Ei vasta lopussa, vaan väliarvioinnit koko matkan, että kaikki tietää miten mennään. Ja ennen kaikkea: jokainen saa valita mihin projektiin osallistuu. Kaikki osallistuu ainakin yhteen kehitysryhmään, ei jäädä sivuun. Se on se keskinäinen riippuvuus, mitä Aino sanoi.",
    costUSD: 0.0057357,
  },
  {
    speaker: "Aino",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "challenge",
    said: "Nea, sä sanoit että divergenssivaiheessa kaikki saa sanoa mitä mieltä on ja ettei ketään jäädä sivuun — mut entä jos joku ei halua osallistua, esimerkiksi koska on väsynyt tai epäluuloinen kehityshankkeista? Miten se, että jokainen valitsee mihin projektiin osallistuu, toimii jos ilmoittautuminen on vapaaehtoista?",
    costUSD: 0.0036499,
  },
  {
    speaker: "Nea",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "build",
    said: "No, joo, se on oikeasti hyvä pointti. Mun kappaleessa sanotaan että jokainen valitsee mihin projektiin osallistuu neljästä-viidestä tärkeimmästä sovitusta kehityskohteesta. Eli ei ole vapaaehtoista että osallistuuko vai ei — jokainen osallistuu johonkin, mutta voi valita mihin. Se on tavallaan pakollista vapaavalintaisuutta. Mut tuo sun kysymys siitä, mitä tapahtuu jos joku ei silti halua — että voiko väsymyksestä tai epäluulosta johtua passiivisuutta — sitä mun kappale ei käsittele. Mut veikkaisin että tähän liittyy se, mitä Aino sanoi siitä turvallisuuden tunteen rakentamisesta. Jos johtaja on oikeasti kuunnellut ja reflektio on jokapäivästä, niin ehkä väsymys ja epäluulo vähenee.",
    costUSD: 0.0046377,
  },
  {
    speaker: "Leo",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "challenge",
    said: "Nea, hyvä selitys. Sä sanoit että konvergenssissä valitaan vain neljä-viisi tärkeintä kehityskohdetta, ettei aloiteta liian montaa kerralla — mut miten se päätetään, mitkä nuo kohdat valitaan? Liittyykö siihen siihen divergenssissä kerättyyn palautteeseen, vai kuka tekee sen valinnan?",
    costUSD: 0.0041829,
  },
  {
    speaker: "Nea",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "build",
    said: "Niin, hyvä kysymys Leo. Mun kappaleessa sanotaan että konvergenssissa osapuolet sopivat kehitysongelmista yhdessä ja niiden prioriteetista. Eli se valinta tehdään yhdessä koko yhteisön kanssa, ei että johtaja päättää yksin. Divergenssissa kerätty palaute ja näkökulmat muodostavat pohjan sille päätökselle. Mun kappaleessa mainitaan vielä että johtajalla pitää olla kyky asettaa prioriteetteja yhdessä kaikkien osapuolten kanssa. Niin että se päätös syntyy siitä, mitä divergenssissa tuli ilmi — vahvuuksista, kehitystarpeista, strategiasta — mutta sitä neuvotellaan ja sovitaan yhdessä, ei määrätä vaan ylhäältä päin.",
    costUSD: 0.0048766999999999994,
  },
  {
    speaker: "Teacher",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "facilitate",
    said: "Sami, sun vuoro: opeta kappaleesi \"Cooperative development of a work community\" ryhmällesi.",
    costUSD: null,
  },
  {
    speaker: "Sami",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "propose",
    docRef: "b",
    said: "Okei, joten mun kappale käsittelee sitä, miten yhteisö kehittyy kooperatiivisesti. Siis miten se ei oo vaan se, että johtaja sanoo mitä tehdään, vaan miten koko työyhteisö yhdessä päättää mihin suuntaan mennään ja miten sinne päästään.\n\nJäävuoren malli on tässä avainasemassa. Näkyvät jutut – ongelmat, ratkaisut, rakenteet – ne on vain pinta. Oikea muutos tapahtuu alla: arvoissa, kommunikaatiossa, siinä miten ihmiset liittyvät toisiinsa. Ja siihen pääsee vain sillä, että kaikki osallistuu prosessiin alusta.\n\nSitten on tämä divergenssi-konvergenssi-sykli. Divergenssi tarkoittaa sitä, että ensin avataan keskustelu – miten asiat vois olla, mitä ongelmia on, miten me kokemme tilanteen. Se on avointa, generatiivista. Sitten konvergenssi – siis lopuksi sovitaan yhdessä mitkä asiat on tärkeimmät ja missä järjestyksessä niitä viedään eteenpäin.\n\nJa tämä kaiken alla on tämä Kolbin oppimissykli – kokemus, reflektio, teoria, testaus, uusi kokemus. Eli kehitys ei oo kertasuoritus vaan sykliä, joka jatkuu.\n\nTärkeää on myös se, että jokainen vastaa jostain – sovitaan etukäteen kuka tekee mitä, mitkä on onnistumisen kriteerit. Ja arvioidaan jatkuvasti, ei vaan lopussa. Ilman sitä ihmiset unohtaa mistä lähdettiin ja motivaatio katoaa.",
    costUSD: 0.0051575,
  },
  {
    speaker: "Vilma",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "challenge",
    said: "Joo, kiitos Sami hyvästä selvityksestä! Mut nyt mä jäin miettimään tätä divergenssi-konvergenssi-sykliä – kun sä sanoit että divergenssissa avataan keskustelu ja konvergenssissa sovitaan yhdessä, niin miten käytännössä johtaja tietää milloin siihen divergenssiin on ollut tarpeeksi? Eli koska se on aika auki, eikö siinä voi jäädä kiertämään pitkäksi ja ihmisiä frustroituu että ei päästä mihinkään?",
    costUSD: 0.0038919000000000002,
  },
  {
    speaker: "Sami",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "build",
    said: "Joo, ihan validi huoli. Mun kappaleessa käy ilmi että divergenssi on rajattu – siis sen alussa sovitaan tietyt cooperative techniques mitä käytetään, ongelmakartoitus tai kyselyt tai ohjattu keskustelu. Ja sitten kun saadaan tarpeeks tietoa ja erilaisia näkemyksiä, siirrytään konvergenssiiin eli siis sovitaan yhdessä. Tässä johtajalla on tärkeä rooli – hän näkee koko ajan missä mennään ja tietää milloin on aika siirtyä seuraavaan vaiheeseen. Mut nyt en ole varma jos mun kappale käsittelee sitä, miten pitkä divergenssi voi olla. Veikkaisin että sen mittaa lähinnä sillä missä vaiheessa ihmiset alkaa toistaa itseään ja että pääväitteet on jo selillään – eli siis ajankäyttö on tavallaan luontevaa eikä niin, että vaan väännetään samaa asiaa ympyrää.",
    costUSD: 0.0047495,
  },
  {
    speaker: "Otto",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "challenge",
    said: "Joo, hyvä selvitys Sami! Mut nyt musta jäi epäselväks tämä yksilöllinen vastuu – kun sä sanoit että jokainen vastaa jostain ja sovitaan etukäteen kuka tekee mitä, niin miten se toimii silloin kun jonkun tehtävä pettää tai ihminen ei tee sitä mitä lupasi? Siis käytkö siihen puuttumisen mun kappaleen sopeutumisen kautta vai onko se enemmän reflektiota ja arviointia joka tapahtuu joka kokoontuessa?",
    costUSD: 0.0045153,
  },
  {
    speaker: "Sami",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "build",
    said: "Joo, Otto, hyvä kysymys. Mun kappaleessa tämä käsitellään sillä, että arviointia tapahtuu koko prosessin ajan, ei vaan lopussa. Eli jos jonkun tehtävä pettää, se tulee esiin näissä väliarvioinnissa, ja silloin käydään reflektio – miksi näin kävi, mitä tarvitaan, miten tuetaan. Tää jatkuva arviointi on siis keino nähdä ongelmat ajoissa. Mutta varsinaisesti siitä, miten käytännössä puututaan esimerkiksi siihen että ihminen ei tee sovittua, mun kappale ei ihan konkreettisesti käy läpi. Veikkaisin että se liittyy siihen jatkuvaan dialogiin ja konfliktien ratkaisuun mitä Vilma mainitse, mut en ole siitä varma.",
    costUSD: 0.0049435,
  },
  {
    speaker: "Teacher",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "facilitate",
    said: "Leo, sun vuoro: opeta kappaleesi \"Good meeting practises as an example of cooperative leadership\" ryhmällesi.",
    costUSD: null,
  },
  {
    speaker: "Leo",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "propose",
    docRef: "c",
    said: "Okei, niin mun kappale käsittelee sitä, miten kokouskulttuurilla voidaan rakentaa koko organisaation yhteistyökykyä. Ja tää on oikeesti näyttävä idea — hyvin johdettu kokous on niinku pienoismallit siitä, miten yhteisöllinen johtaminen toimii käytännössä.\n\nNiin, aluksi tärkein juttu on fyysinen ympäristö. Kun istutaan ympyrässä ilman pöytiä eikä eri puolilla huonetta, se muuttaa dynamiikkaa todella paljon. Se varmistaa että kaikki näkee toisensa ja kuuluu paremmin. Ja vielä parempi — ei ole sidottu siihen että istuu aina samalla paikalla, voidaan kokeilla uutta paikkaa tai jopa mennä ulos pihoille. Se avaa ajattelua.\n\nSitten agendajako on isossa roolissa. Agenda jaetaan kolmeen osaan: ilmoituksiin, päätettäviin asioihin ja keskusteltaviin asioihin. Näin aika ei hukkaudu siihen että kerrotaan asioita mitä olisi voitu laittaa paperille. Ja aika sovitaan etukäteen — kaikki tietää milloin lähdetään, niin keskustelu on kurinalaista.\n\nMut kaikkein tärkein on osallistaminen. Kun on vaikeita asioita, käytetään parityöskentelyn ja pienryhmien kautta — näin hiljaisetkaan eivät jää sivuun. Esimerkiksi jos jotkut ihmiset ei puhu kokouksissa, niin heidät laitetaan pariin miettimään asiaa, ja sitten satunnaisesti jokin parista raportoi. Se takaa että jokaisen ääni kuuluu.\n\nJa lopuksi — kokoukset arvioidaan pareissa, mihin me onnistuimme, mihin ei. Se arviointikulttuuri pitää kokoukset kehittymässä.",
    costUSD: 0.0067829,
  },
  {
    speaker: "Aino",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "challenge",
    said: "Leo, sä sanoit että kun käytetään parityöskentelyä ja pienryhmiä, niin hiljaisetkaan eivät jää sivuun — mut entä jos joku ihminen on niin hiljainen tai vetäytynyt, ettei osallistu edes parityöskentelyyn? Vai toimiiko se parityöskentely sinänsä niin hyvin että siihen sitoutuminen tulee automaattisesti?",
    costUSD: 0.004995899999999999,
  },
  {
    speaker: "Leo",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "build",
    said: "Niin joo, se on hyvä kysymys Aino. Mun kappaleessa sanotaan että parityöskentely ja pienryhmät tekee sen osallistamisen helpommaksi, mut ei se automaattisesti ratkaise sitä, jos joku on oikeasti vetäytynyt. Mun kappaleessa mainitaan että jos joku ei osallistu aktiivisesti, se ei tarkoita ettei heillä olis mielipidettä — se on enemmän että organisaatiossa on totuttu siihen että vaan osa puhuu. Mut se konkreettinen tilanne, että joku ei osallistu edes parityöskentelyyn, sitä mun kappale ei käsittele. Mut mä kuitenkin veikkaisin että jos se turvallisuuden tunne ja luottamus on rakennettu hyvin, mihin Aino viittasi, niin sekin estävä tekijä vähentyy. Se tarvii kuitenkin aikaa ja johdonmukaista pyrkimystä.",
    costUSD: 0.0060319,
  },
  {
    speaker: "Nea",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "challenge",
    said: "Leo, sä sanoit että kokouksen fyysinen ympäristö muuttaa dynamiikkaa — että ympyrän istumajärjestys ja se ettei ole pöytiä, niin kaikki näkee toisensa paremmin. Mut voitko antaa jonkun konkreettisen esimerkin siitä, miten se ympyrä tai se pihan käyttö oikeasti muutti sitä, miten ihmiset osallistuu ja kuuntelee toisiaan? Niinku, onko siihen liittynyt jotain konkreettista näyttöä siitä että tämä paikan vaihtaminen tekee oikeasti eroa?",
    costUSD: 0.0058387,
  },
  {
    speaker: "Leo",
    phase: "opetus",
    group: "ryhma1",
    dialogueMove: "build",
    said: "Niin joo, Nea, se on tosi hyvä kysymys. Mun kappaleessa sanotaan että ympyrän istumajärjestys ja pöytien poistaminen tekee vuorovaikutuksesta tehokkaampaa, ja että se paikan uudistaminen — esimerkiksi istuminen ulos puutarhassa — avaa ajattelua. Mut konkreettista näyttöä siitä, miten se muutti osallistumista, sitä mun kappaleessa ei ihan ole. Se enemmän sanoo että kokemukset on osoittaneet että se toimii ja että prosessin jälkeen kannattaa arvioida yhdessä, mitkä oli plussat ja mitkä miinukset. Mut et, tää idea että fyysinen muutos auttaa — se on kyl uskottava, koska kun ihmiset näkevät toisensa silmästä silmään ympyrässä, niin se tavallaan pakottaa kuuntelemaan paremmin eikä voi vaan istua hiljaa ja olla läsnä.",
    costUSD: 0.006512899999999999,
  },
  {
    speaker: "Teacher",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "facilitate",
    said: "Otto, sun vuoro: opeta kappaleesi \"Good meeting practises as an example of cooperative leadership\" ryhmällesi.",
    costUSD: null,
  },
  {
    speaker: "Otto",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "propose",
    docRef: "c",
    said: "Okei, joten mun kappale käsittelee sitä, miten kooperatiivinen johtajuus näkyy käytännössä kokouksissa ja palavereissa. Ja Leppilampi sanoo että huonot kokoukset on oikeesti organisaatioiden suurin ajan hukkaaminen – ne alkaa myöhässä, vaan muutama puhuu, keskustelu hyppii aiheesta toiseen. Ja tää kuulostaa pieneltä asialta, mutta Leppilampi näkee että kokoukset on niinku miniatyyrimalli siitä, miten organisaatiossa toimitaan yleensä.\n\nTärkeimmät jutut on kolme. Ensinnäkin fyysinen ympäristö ja aika. Missä istutaan ja miten aika järjestetään, se tavallaan viesti rakenteesta. Parempi istua ympyrässä ilman pöytää, ja aika pitää sopia etukäteen ja pitää sitä. Varsinkin tärkeää on että kaikki pääsee osallistua alusta loppuun.\n\nToinen juttu on osallistuminen. Leppilampi sanoo että monet ihmiset ei puhu kokouksissa, mut se ei tarkoita ettei heillä ois ajatuksia. Niin käytetään pari-keskusteluja, pienryhmiä, ja näitä \"kirjain-rooleja\" – esim A, B, C – joissa jokainen ryhmän jäsen voi olla ääneen ihminen. Näin varmistetaan se periaate \"everyone is ready to report\", eli kaikki joutuu olemaan valmis selittämään ryhmän mielipidettä.\n\nKolmanneksi agenda pitää jakaa osiin: ilmoitukset, päätettävät asiat, keskusteltavat asiat. Ja aika arvioida – miten onnistuimme? Ja suunnitella seuraava kokous. Nämä viimeiset osat usein jätetään tekemättä, mut ne on kriittisiä.\n\nYdinasia siis on että positiivinen keskinäisriippuvuus ja yksilöllinen vastuu, mitkä oli Vilman ja Samin kappaleissa, ne tulee oikein konkreettisiksi kokouksen käytännöissä.",
    costUSD: 0.0073003,
  },
  {
    speaker: "Vilma",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "challenge",
    said: "Joo, kiitos Otto hyvästä selityksestä! Mä jäin erityisesti miettimään tätä pari-keskusteluja ja näitä \"kirjain-rooleja\" – kun sä sanoit että näin varmistetaan se, että kaikki joutuu olemaan valmis selittämään ryhmän mielipidettä, niin voiko siitä tulla väärinkään? Siis jos ryhmän sisällä on ihmisiä jotka on silti erimielisiä, niin eikö se \"jokainen raportoija\" -periaate vaan peitä niitä erilaisia näkemyksiä sen pari-keskustelussa sovitulla yhteisellä linjalla?",
    costUSD: 0.005596899999999999,
  },
  {
    speaker: "Otto",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "build",
    said: "Joo, se on hyvä kriittinen kysymys Vilma. Mun kappaleessa se ei käsittele sitä, että mitä tapahtuu jos ryhmän sisällä on oikeesti syviä erimielisyyksiä. Mut Leppilampi kyllä painottaa että nämä pari-keskustelut ja kirjain-roolit ei peittää erilaisia näkemyksiä – ne pikemminkin varmistaa että ne erilaiset näkemykset saavat äänen, koska ne hiljaisetkin ihmiset joutuu olemaan valmiita raportoimaan. Mut mä veikkaisin että jos ero on oikeesti radikaali, niin se tulee siinä raportointivaiheessa esiin – että ryhmä sanoo suoraan että 'meillä ei ollut yksimielisyyttä tässä'. Eli kyllä se pitäis näkyä, ei peittyä.",
    costUSD: 0.0062213,
  },
  {
    speaker: "Sami",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "challenge",
    said: "Joo, Otto, ihan kiinnostava näkökulma nää kokouskäytännöt. Mut nyt mä jäin miettimään sitä, kun sä sanoit että fyysinen ympäristö ja aika on kriittistä – jos jostakin syystä sitä ei voi muuttaa, esimerkiksi iso organisaatio jossa on pöydät ja aika on kiinni, niin voiko siitä silti tulla kooperatiivista palaveria vai onko se kuitenkin täysin mahdotonta?",
    costUSD: 0.0058215,
  },
  {
    speaker: "Otto",
    phase: "opetus",
    group: "ryhma2",
    dialogueMove: "build",
    said: "Joo, hyvä pointti Sami. Mun kappaleessa se ei käsittele sellasta tilannetta että pöydät on kiinni ja ajan aikataulut on jo määrätty. Mut Leppilampi kyllä korostaa että nuo fyysiset jutut — ympyrä, aika, tilaisuus puhua — ne on keinoja siihen että kaikki voi oikeesti osallistua. Joten jos ne puuttuu, niin se varmaan vaikeuttaa sitä. Mutta veikkaisin että tärkeempää ois silti muuttaa sitä, miten kokousta johdetaan — eli ne pari-keskustelut ja kirjain-roolit vois toimia silti, vaikka istuttaisiin pöydän ääressä. Se fyysinen juttu on tukea, ei itse asia.",
    costUSD: 0.0065123,
  },
  {
    speaker: "Teacher",
    phase: "synteesi",
    dialogueMove: "facilitate",
    said: "Kaikki kolme kappaletta on nyt opetettu molemmissa ryhmissä. Lopuksi synteesi: pyydän jokaista kertomaan omin sanoin, miten ymmärsitte kaikki kolme teemaa — myös ne kaksi, joita ette itse lukeneet.",
    costUSD: null,
  },
  {
    speaker: "Teacher",
    phase: "synteesi",
    group: "ryhma1",
    dialogueMove: "facilitate",
    said: "Aino, kerro omin sanoin: miten sä ymmärsit nää kolme teemaa kokonaisuutena?",
    costUSD: null,
  },
  {
    speaker: "Aino",
    phase: "synteesi",
    group: "ryhma1",
    dialogueMove: "integrate",
    said: "Niin, mä yritän nyt kytkeä nää kolme teemaa yhteen. Tuntuu sille, että ne kulkee samaa rataa: kaikissa on se idea, että johtajuus ei oo käskemistä vaan osallistamista ja yhteistä pohtimista.\n\nAino kertoi siitä, että johtaja kävelee henkilöstön rinnalla ja kysyy kysymyksiä — että se oppiminen, se experiential learning, vaatii sitä että ihmiset itse reflektoi omaa tekemistään. Nea sitten näytti, miten se todellisuudessa tapahtuu: että divergenssivaiheessa kaikki sanoo mielipiteensä, ja sitten konvergenssissa sovitaan yhdessä mitkä kehityskohdat otetaan mukaan. Se on käytännön toteutus siitä, mitä Aino sanoi.\n\nJa Leo sanoi, että kokouskulttuurilla rakennetaan tätä samaa asiaa pienemmässä mittakaavassa — että hyvässä kokouksessa ihmiset näkee toisensa, istuu ympyrässä, ja parityöskentelyllä varmistetaan että kaikki osallistuu.\n\nMikä niitä yhdistää, on se keskinäinen riippuvuus ja turvallisuuden tunne. Mutta myös se, mikä jäi miettityttämään: miten tää toimii silloin kun joku ihminen on oikeasti vastustava tai väsynyt? Kaikissa teemoissa me sanottiin, että luottamus on pohja, mutta mun kappaleista ei oikeasti käynyt ilmi, miten siihen luottamukseen päästään jos se ei jo ole olemassa.",
    costUSD: 0.0077049,
  },
  {
    speaker: "Teacher",
    phase: "synteesi",
    group: "ryhma1",
    dialogueMove: "facilitate",
    said: "Nea, kerro omin sanoin: miten sä ymmärsit nää kolme teemaa kokonaisuutena?",
    costUSD: null,
  },
  {
    speaker: "Nea",
    phase: "synteesi",
    group: "ryhma1",
    dialogueMove: "integrate",
    said: "Niin, mä yritän nyt jäsentää nää kolme teemaa yhteen. Tuntuu sille, että ne kaikki käsittelee samaa asiaa eri tasoisesti — miten organisaatiossa rakennetaan sellainen kulttuuri, jossa ihmiset oikeasti osallistuu ja oppii yhdessä.\n\nAino puhui siitä, että johtaminen on reflektointia ja kysymysten esittämistä, ei käskemistä. Mulla oli se kohta, miten se oikeasti toteutetaan käytännössä — että divergenssissa kuunnellaan kaikkia eikä jäädä ketään sivuun, ja sitten konvergenssissa sovitaan yhdessä mitkä asiat otetaan mukaan. Se on se, miten Ainon ideasta tulee todellinen prosessi. Ja Leo näytti, kuinka samaa logiikkaa sovelletaan kokouksissa — fyysinen ympäristö ja parityöskentely varmistaa että kaikki kuuluu ja osallistuu.\n\nMikä niitä kaikki kolmea yhdistää, on se positiivinen keskinäisriippuvuus ja turvallisuus. Mut mä jäin miettimään sitä, mitä Aino mainitsikin — miten tähän päästään organisaatiossa, joka ei vielä toimi näin? Että miten siihen luottamukseen ja turvallisuuteen päästään, jos se ei ole valmiina?",
    costUSD: 0.0080017,
  },
  {
    speaker: "Teacher",
    phase: "synteesi",
    group: "ryhma1",
    dialogueMove: "facilitate",
    said: "Leo, kerro omin sanoin: miten sä ymmärsit nää kolme teemaa kokonaisuutena?",
    costUSD: null,
  },
  {
    speaker: "Leo",
    phase: "synteesi",
    group: "ryhma1",
    dialogueMove: "integrate",
    said: "Niin, mä yritän nyt kytkeä nää kolme teemaa yhteen. Tuntuu sille, että ne kaikki käsittelee samaa asiaa eri tasoilla — miten organisaatiossa rakennetaan sellainen kulttuuri, jossa kaikki oikeasti osallistuu ja oppii yhdessä.\n\nAino puhui siitä experiential learningista, että johtaja ei käske vaan kävelee rinnalla ja kysyy kysymyksiä. Nea näytti sitten, miten tää oikeasti tapahtuu käytännössä — divergenssissä kuunnellaan kaikkia, konvergenssissa sovitaan yhdessä. Ja mun kappale näytti kuinka samaa logiikkaa sovelletaan kokouksissa: pariutat ihmiset, ympyrässä istuminen, jotta kaikki kuuluu ja osallistuu.\n\nMikä niitä kaikki yhdistää, on se positiivinen keskinäisriippuvuus ja se turvallisuuden tunne. Mut mä jäin miettimään sitä, mitä Aino sanoi — miten tähän luottamukseen päästään organisaatiossa, joka ei vielä toimi näin? Se näyttää olevan jotain, mikä pitäisi olla jo olemassa, jotta nää mallit toimii. Mut niinku, mitä tapahtuu jos sitä luottamusta ei ole?",
    costUSD: 0.0083759,
  },
  {
    speaker: "Teacher",
    phase: "synteesi",
    group: "ryhma2",
    dialogueMove: "facilitate",
    said: "Vilma, kerro omin sanoin: miten sä ymmärsit nää kolme teemaa kokonaisuutena?",
    costUSD: null,
  },
  {
    speaker: "Vilma",
    phase: "synteesi",
    group: "ryhma2",
    dialogueMove: "integrate",
    said: "Joo, okei. Niin kyl mä näen tässä yhteisen langan kaiken läpi. Se on se, että kooperatiivinen johtajuus ei ole yksittäinen juttu vaan se on prosessi, jossa kaikki osallistuu ja oppii yhdessä. Vilman kappaleesta tuli selväksi se, että johtaja on tavallaan mallina – hän myöntää omat heikkoutensa ja näyttää että epäonnistuminen on ok. Ja Samin kautta ymmärrän, että tää ei oo vaan hyvä mieli vaan se vaatii varsinaista rakennetta, sitä divergenssi-konvergenssia, jatkuvaa arviointia.\n\nOtto toi sit konkreettisesti esiin sen, että nää jutut näkyy kokouksissa – miten istutaan, miten aika käytetään, että kaikki pääsee siihen mukaan. Mut siis yhdistävä asia näiden kolmen kautta on se positiivinen keskinäisriippuvuus ja se, että jokainen on vastuussa. Johtaja ei vaan johda vaan jalkauttaa sitä kulttuuria, Sami näytti että se vaatii järjestelmällisiä välineitä, ja Otto näytti että se on nähtävissä jokapäiväisissä kokouksissa.\n\nMut nyt jää mua mietityttämään se, että miten käytännössä tämä liikkeelle pääsee, jos organisaatiossa on jo paljon epäluottamusta tai pelkoa. Tavallaan se tuntuu että tässä kaikessa oletetaan jo jonkinlainen perusta olemassa. Mutta se on varmaan se, mikä kehityksessä tapahtuu ajan myötä.",
    costUSD: 0.0079139,
  },
  {
    speaker: "Teacher",
    phase: "synteesi",
    group: "ryhma2",
    dialogueMove: "facilitate",
    said: "Sami, kerro omin sanoin: miten sä ymmärsit nää kolme teemaa kokonaisuutena?",
    costUSD: null,
  },
  {
    speaker: "Sami",
    phase: "synteesi",
    group: "ryhma2",
    dialogueMove: "integrate",
    said: "Joo, okei. Niin mä näen tässä oikeastaan yhden isomman systeemin, joka rakentuu kolmella tasolla. Vilman kappaleesta tuli selväks se, että johtaja on tavallaan katalayytti – hän näyttää esimerkillä että epäonnistuminen on ok, että reflektio ja oppiminen on kulttuurissa sallittua. Ja mun kappale tuo sitten sen, että tämä kulttuurin muutos vaatii oikeesti järjestelmällisiä välineitä – divergenssi-konvergenssia, jatkuvaa arviointia, selkeitä vastuita. Se ei oo vaan hyviä aikeitä vaan rakennetta.\n\nOtto tuo sit käytännön tasoon – että nämä kaikki jutut, positiivinen keskinäisriippuvuus ja vastuu, ne näkyy konkreettisesti siinä, miten kokous pidetään, kuka saa puhua, miten aika käytetään. Tavallaan Otto näyttää että mikropöly paljastaa isomman systeemin.\n\nMut nyt jää mua hiukan mietityttämään se, että artikkelissa kaikissa kolmessa kappaleessa tavallaan oletetaan jo se, että ihmiset haluaa osallistua ja oppii. Mitä tapahtuu jos organisaatiossa on syvää epäluottamusta tai pitkän aikaa käytetty hierarkkista mallia? Miten se divergenssi-konvergenssi oikeasti liikkeelle pääsee silloin? Se on varmaan se prosessi mitä tapahtuu, mut se tuntuu olevan vähän näkymätön tässä materiaalissa.",
    costUSD: 0.0083745,
  },
  {
    speaker: "Teacher",
    phase: "synteesi",
    group: "ryhma2",
    dialogueMove: "facilitate",
    said: "Otto, kerro omin sanoin: miten sä ymmärsit nää kolme teemaa kokonaisuutena?",
    costUSD: null,
  },
  {
    speaker: "Otto",
    phase: "synteesi",
    group: "ryhma2",
    dialogueMove: "integrate",
    said: "Joo, kiitos. Niin mä näen tässä oikeastaan yhden koheesiivisen systeemin, joka rakentuu alhaalta ylöspäin. Vilman kappaleesta tuli selväks se, että johtaja on tavallaan mallin antaja — hän näyttää esimerkillä että epäonnistuminen on ok, että reflektio ja avoin puhuminen on sallittua. Ja se on kriittistä, koska se luo sen perustan mihin kaikki muu rakentuu.\n\nSamin kappale tuo sitten sen, että tämä kulttuuri ei syntyperäis itsestään vaan se vaatii oikeesti järjestelmällisiä välineitä — divergenssi-konvergenssia, jatkuvaa arviointia, selkeitä vastuita. Se ei oo vaan johtajan hyvät aikomukset vaan rakenteita ja prosesseja.\n\nJa mun kappale — siis nämä kokouskäytännöt — ne on tavallaan paikka missä nämä molemmat konkretisoituu päivittäisessä arjessa. Kun istutaan ympyrässä, kun käytetään pari-keskusteluja ja kirjain-rooleja, niin se on siinä se positiivinen keskinäisriippuvuus ja vastuu näkyvästi läsnä.\n\nMut mikä mua hiukan mietityttää on se, että kaikissa kolmessa kappaleessa tavallaan oletetaan jo se perusta olemassa — että ihmiset haluaa osallistua, että he luottaa johtajaan. Mitä tapahtuu jos organisaatiossa on syvää epäluottamusta tai parikymmentä vuotta hierarkkista mallia taustalla? Miten se liikkeelle oikeastaan pääsee? Se on varmaan se muutosprosessi mitä tapahtuu, mut se tuntuu olevan näissä kappaleissa vähän näkymätön.",
    costUSD: 0.009357299999999999,
  },
  {
    speaker: "Teacher",
    phase: "synteesi",
    dialogueMove: "facilitate",
    said: "Kiitos kaikille — hieno sessio! Tässä näkyi palapelimenetelmän ydin: kukaan ei olisi voinut oppia tätä kokonaisuutta yksin.",
    costUSD: null,
  },
];
